
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = controller
src_dir = ${PROJECT_DIR}/controller/src
include_dir = ${PROJECT_DIR}/controller/include

[env]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1-n8r8v
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 115200
upload_protocol = esptool
upload_flags = 
    --before=default_reset
    --after=hard_reset
build_type = debug

lib_extra_dirs =
    ${PROJECT_DIR}/shared
    ${PROJECT_DIR}/../shared
    ${PROJECT_DIR}/sensors

[env:manager]
lib_deps =
    kosme/arduinoFFT@^2.0
    WebSockets @^2.3.6
    ArduinoJson @^6.18.5
    PubSubClient
build_flags = 
    ; PINS
    -D PIN_MIC_SCK=7
    -D PIN_MIC_WS=6
    -D PIN_MIC_SD=4
    -D PIN_MODE=-1
    -D MANAGER_PORT=8081

    -D I2C_SPEED=400000
    -D MQTT_BUFFER_SIZE=4096
    -D SERIAL_BAUD=115200

    -D CORE_DEBUG_LEVEL=5
    -I${PROJECT_DIR}
    -I${PROJECT_DIR}/manager/include
    -I${PROJECT_DIR}/shared/include
    -I${PROJECT_DIR}/../shared/include
    -I${PROJECT_DIR}/sensors/microphone

src_dir = manager/src
include_dir = manager/include

build_src_filter = 
    +<manager/src/*.cpp>  ; Controller source files
    +<shared/src/*.cpp>      ; Shared source files
    +<../shared/src/*.cpp>   ; Shared source files
    +<sensors/*.cpp>         ; Sensor files
    -<*/test/*>              ; Exclude test directories
    -<*/tests/*>

[env:controller]
lib_deps = 
    waspinator/AccelStepper @ ^1.64
    adafruit/Adafruit MCP4728 @ ^1.0.5
    adafruit/Adafruit BusIO @ ^1.14.1
    SPI
    Wire
    EEPROM
    Preferences
build_flags = 
    ; PINS
    -D PIN_SCL=8
    -D PIN_SDA=18
    -D PIN_SUPPLY_0_EN=2
    -D PIN_SUPPLY_1_EN=1
    -D PIN_SUPPLY_0_CURR_SENSE=-1
    -D PIN_SUPPLY_1_CURR_SENSE=-1
    -D PIN_MOTOR_EN=13
    -D PIN_MOTOR_STEP=11
    -D PIN_MOTOR_DIR=12
    -D PIN_MODE=10

    -D SERIAL_BAUD=115200
    -D I2C_SPEED=400000

    -D CORE_DEBUG_LEVEL=5
    -I${PROJECT_DIR}
    -I${PROJECT_DIR}/controller/include
    -I${PROJECT_DIR}/shared/include
    -I${PROJECT_DIR}/../shared/include
    -I${PROJECT_DIR}/sensors/distance

build_src_filter = 
    +<controller/src/*.cpp>      # Controller-specific files
    +<shared/src/*.cpp>          # Local shared files
    +<../shared/src/*.cpp>       # Parent shared files
    +<sensors/*.cpp>             # Sensor files
    -<*/test/*>
    -<*/tests/*>
